[project]
name = "keypal"
version = "0.2.0"
description = "Learn the keyboard shortcuts for common apps"
readme = "README.md"
license = "MIT"
authors = [
    { name = "Trey Hunner" }
]
requires-python = ">=3.14"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: X11 Applications :: Qt",
    "Topic :: Education",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "fsrs>=6.3,<7",
    "platformdirs>=4.9.6",
    "PySide6>=6.7",
]

[project.scripts]
keypal = "keypal.app:main"

[project.urls]
Homepage = "https://github.com/treyhunner/keypal"
Repository = "https://github.com/treyhunner/keypal"
Issues = "https://github.com/treyhunner/keypal/issues"

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "briefcase>=0.4.2",
    "pytest>=9.0.3",
    "pytest-qt>=4.4",
    "ruff>=0.15.12",
]

[tool.briefcase]
project_name = "KeyPal"
bundle = "io.github.treyhunner"
version = "0.2.0"
author = "Trey Hunner"
author_email = "trey@treyhunner.com"

[tool.briefcase.app.keypal]
formal_name = "KeyPal"
description = "Learn the keyboard shortcuts for common apps"
sources = ["src/keypal"]
requires = [
    "fsrs>=6.3,<7",
    "platformdirs>=4.9.6",
    "PySide6>=6.7",
]

[tool.briefcase.app.keypal.macOS]
min_os_version = "12.0"

[tool.briefcase.app.keypal.linux]
flatpak_runtime = "org.kde.Platform"
flatpak_sdk = "org.kde.Sdk"
flatpak_runtime_version = "6.10"

